services:
  bot:
    build: .
    container_name: telegram-stats-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PORT=3000
    volumes:
      - ./data:/app/data # сохраняем базу данных локально
